#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${1:-/shared/shen/cpu_ai_drug_design}"

FILES=(
  "README.md"
  "config.yaml"
  "Snakefile"
  "run_workflow.py"
  "00_docs/PROJECT_STRUCTURE.md"
  "00_docs/PIPELINE_OVERVIEW.md"
  "00_docs/BENCHMARK_PLAN.md"
  "00_docs/MODULE_INTERFACES.md"
  "00_docs/ARTIFACT_SCHEMAS.md"
  "00_docs/REAL_BACKEND_STATUS.md"
  "00_docs/BENCHMARK_CASE_SCHEMA_V2.md"
  "00_docs/RUN_RECOVERY.md"
  "04_metadata/README.md"
  "04_metadata/FIELD_REFERENCE.md"
  "04_metadata/targets.tsv"
  "04_metadata/compound_libraries.tsv"
  "04_metadata/benchmark_cases.tsv"
  "04_metadata/benchmark_case_truth.tsv"
  "03_data_raw/targets/BRD4_BD1_4QZS.pdb"
  "03_data_raw/targets/BRD4_BD1_4C66.pdb"
  "03_data_raw/targets/BRD2_BD2_3ONI.pdb"
  "03_data_raw/targets/BRDT_BD1_4FLP.pdb"
  "03_data_raw/targets/BRD3_BD1_3S91.pdb"
  "03_data_raw/targets/BRD3_BD2_3S92.pdb"
  "03_data_raw/targets/BRD2_BD1_2YEK.pdb"
  "03_data_raw/targets/BRD3_BD1_24OS.pdb"
  "03_data_raw/targets/PXR_LBD_8F5Y.pdb"
  "03_data_raw/compound_libraries/BRD4_LIT_FOCUSED_001.smi"
  "03_data_raw/compound_libraries/BRD4_LIT_FOCUSED_002.smi"
  "01_tools/validate_metadata.py"
  "01_tools/generate_run_manifest.py"
  "01_tools/case_scoped_cleanup.py"
  "01_tools/build_enhancement_comparison.py"
  "01_tools/build_enhancement_iteration_tracker.py"
  "08_envs/environment.cpu.yaml"
  "09_reports/README.md"
  "09_reports/workflow_summary_draft.md"
  "09_reports/module_status_table_draft.md"
  "06_scripts/modules/_module_stub.py"
  "06_scripts/modules/target_preparation.py"
  "06_scripts/modules/compound_library_preparation.py"
  "06_scripts/modules/classical_docking.py"
  "06_scripts/modules/ai_reranking.py"
  "06_scripts/modules/filtering.py"
  "06_scripts/modules/clustering_and_prioritization.py"
  "06_scripts/modules/report_generation.py"
  "06_scripts/modules/benchmark_evaluation.py"
  "06_scripts/modules/run_state_checker.py"
  "08_envs/slurm.run_workflow.sbatch"
)

for file in "${FILES[@]}"; do
  hpc-put "$file" "$PROJECT_ROOT/$file"
done
