name: singlecell-workbench-py311
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.11
  - pip
  - anndata=0.12.10
  - boto3
  - click>=8.1
  - gdown
  - h5py>=3.10
  - igraph
  - jinja2>=3.1
  - leidenalg
  - matplotlib>=3.8
  - mudata=0.3.3
  - muon
  - nbformat>=5.10
  - numpy>=1.26
  - openpyxl
  - pandas>=2.2
  - pytorch=2.5
  - cpuonly
  - pyyaml>=6.0
  - requests
  - scanpy=1.11.5
  - scikit-misc
  - scipy>=1.11
  - scvi-tools=1.4.2
  - seaborn>=0.13
  - tabulate
  - pytest>=8.0
